### ISSUE TITLE
ninja: error: 'device/generic/goldfish/fstab.goldfish', needed by ... missing and no known rule to make it

### ISSUE THREAD

**Issue by crushedice2000** [lj50036/android_device_vendor_codename#2]
I'm trying to port TWRP for the Huawei Ascend G740, and while running `mka recoveryimage` I get the following error:

    ninja: error: 'device/generic/goldfish/fstab.goldfish', needed by '/home/user/android/out/target/product/ascendg740/root/fstab.goldfish', missing and no known rule to make it

It seems weird because I don't state the need for `goldfish` (emulator) files. Maybe I'm doing something wrong.

**Comment by lj50036** [comment]
Can you send me a hangout message, that would make this easier. Thx Josh

**Comment by crushedice2000** [comment]
Fixed by adding the goldfish repository and creating some files with `touch`. However this solution is weird. This probably needs further investigation. Feel free to close the issue if you can't reproduce the problem.
